#!/usr/bin/env bash
# Generate coturn config for remote WebRTC (TURN relay on the Jetson public IP).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_OUT="${ROOT}/turnserver.generated.conf"

PUBLIC_HOST="${WEBRTC_PUBLIC_HOST:-140.123.105.214}"
TURN_USER="${WEBRTC_TURN_USERNAME:-webrtc}"
TURN_PASS="${WEBRTC_TURN_PASSWORD:-}"

if [[ -z "$TURN_PASS" ]]; then
  if [[ -f "${ROOT}/../../sar-stack.env" ]]; then
    # shellcheck source=/dev/null
    source "${ROOT}/../../sar-stack.env"
    TURN_PASS="${WEBRTC_TURN_PASSWORD:-}"
  fi
fi
if [[ -z "$TURN_PASS" ]]; then
  TURN_PASS="$(openssl rand -hex 16)"
  echo "coturn: generated WEBRTC_TURN_PASSWORD=$TURN_PASS (add to sar-stack.env)"
fi

MIN_PORT="${WEBRTC_TURN_MIN_PORT:-49160}"
MAX_PORT="${WEBRTC_TURN_MAX_PORT:-49252}"

cat >"$CONF_OUT" <<EOF
# Generated by configure-coturn.sh — TURN for SAR remote camera
listening-port=3478
listening-ip=0.0.0.0
relay-ip=${PUBLIC_HOST}
external-ip=${PUBLIC_HOST}
realm=edge-ai.basilrari.com
fingerprint
lt-cred-mech
user=${TURN_USER}:${TURN_PASS}
no-cli
no-tls
no-loopback-peers
min-port=${MIN_PORT}
max-port=${MAX_PORT}
verbose
EOF

echo "coturn: wrote $CONF_OUT (public ${PUBLIC_HOST}, user ${TURN_USER})"
echo "WEBRTC_TURN_USERNAME=${TURN_USER}"
echo "WEBRTC_TURN_PASSWORD=${TURN_PASS}"
echo "WEBRTC_TURN_URLS=turn:${PUBLIC_HOST}:3478?transport=udp,turn:${PUBLIC_HOST}:3478?transport=tcp"

cat >"${ROOT}/generated.env" <<EOF
# Source from sar-stack.env or: source Drone_LLM/deploy/coturn/generated.env
export WEBRTC_PUBLIC_HOST=${PUBLIC_HOST}
export WEBRTC_TURN_USERNAME=${TURN_USER}
export WEBRTC_TURN_PASSWORD=${TURN_PASS}
export WEBRTC_TURN_URLS=turn:${PUBLIC_HOST}:3478?transport=udp,turn:${PUBLIC_HOST}:3478?transport=tcp
export WEBRTC_TURN_URL_SERVER=turn:127.0.0.1:3478?transport=udp,turn:127.0.0.1:3478?transport=tcp
export WEBRTC_ICE_TRANSPORT_POLICY=relay
EOF
echo "coturn: wrote ${ROOT}/generated.env (source from sar-stack.env)"
